import type { AppData } from "./types";

const DEFAULT_WORKSPACE_ID = "ws-default";

export const SEED_DATA: AppData = {
  workspaces: [
    {
      id: DEFAULT_WORKSPACE_ID,
      name: "BlackIce",
      color: "#6366f1",
      type: "freelance",
      isActive: true,
      order: 0,
      createdAt: "2025-01-01T00:00:00.000Z",
    },
  ],
  clients: [
    {
      id: "c1",
      workspaceId: DEFAULT_WORKSPACE_ID,
      name: "الجداوي",
      slug: "الجداوي",
      notes: "عميل رئيسي - حملات متعددة سنوياً",
      color: "#6366f1",
      order: 0,
      createdAt: "2025-01-10T10:00:00.000Z",
      styleRefs: [],
    },
    {
      id: "c2",
      workspaceId: DEFAULT_WORKSPACE_ID,
      name: "Cut Salon",
      slug: "cut-salon",
      notes: "صالون حلاقة - محتوى شهري",
      color: "#ec4899",
      order: 1,
      createdAt: "2025-02-05T12:00:00.000Z",
      styleRefs: [],
    },
    {
      id: "c3",
      workspaceId: DEFAULT_WORKSPACE_ID,
      name: "مطعم الديوان",
      slug: "مطعم-الديوان",
      notes: "مطعم فاخر - تصوير أطباق وأجواء",
      color: "#f97316",
      order: 2,
      createdAt: "2025-03-01T08:00:00.000Z",
      styleRefs: [],
    },
  ],
  materials: [
    {
      id: "m1",
      workspaceId: DEFAULT_WORKSPACE_ID,
      clientId: "c1",
      title: "ماتريال حملة رمضان 2025",
      url: "https://drive.google.com/drive/folders/example1",
      shootDate: "2025-03-15",
      type: "project",
      tags: ["رمضان", "حملة", "سوشيال ميديا"],
      description: "كل ماتريال تصوير حملة رمضان - ٣ أيام تصوير",
      isFavorite: true,
      order: 0,
      createdAt: "2025-03-16T14:00:00.000Z",
      updatedAt: "2025-03-16T14:00:00.000Z",
    },
    {
      id: "m2",
      workspaceId: DEFAULT_WORKSPACE_ID,
      clientId: "c1",
      title: "لقطات عامة - مبنى الشركة",
      url: "https://drive.google.com/drive/folders/example2",
      shootDate: "2025-01-20",
      type: "library",
      tags: ["بي رول", "مبنى", "خارجي"],
      description: "لقطات خارجية وداخلية للمبنى - تصلح لأي مشروع",
      isFavorite: true,
      order: 1,
      createdAt: "2025-01-21T10:00:00.000Z",
      updatedAt: "2025-01-21T10:00:00.000Z",
    },
    {
      id: "m3",
      workspaceId: DEFAULT_WORKSPACE_ID,
      clientId: "c2",
      title: "تصوير افتتاح الفرع الجديد",
      url: "https://www.dropbox.com/sh/example3",
      shootDate: "2025-04-01",
      type: "project",
      tags: ["افتتاح", "فرع جديد", "ريلز"],
      description: "تصوير يوم الافتتاح كامل",
      isFavorite: false,
      order: 2,
      createdAt: "2025-04-02T09:00:00.000Z",
      updatedAt: "2025-04-02T09:00:00.000Z",
    },
    {
      id: "m4",
      workspaceId: DEFAULT_WORKSPACE_ID,
      clientId: "c2",
      title: "مكتبة لقطات الصالون",
      url: "https://drive.google.com/drive/folders/example4",
      shootDate: "2025-02-10",
      type: "library",
      tags: ["بي رول", "صالون", "أدوات"],
      description: "لقطات عامة للصالون والأدوات - تستخدم في كل الفيديوهات",
      isFavorite: false,
      order: 3,
      createdAt: "2025-02-11T11:00:00.000Z",
      updatedAt: "2025-02-11T11:00:00.000Z",
    },
    {
      id: "m5",
      workspaceId: DEFAULT_WORKSPACE_ID,
      clientId: "c3",
      title: "تصوير قائمة الطعام الجديدة",
      url: "https://we.tl/t-example5",
      shootDate: "2025-03-20",
      type: "project",
      tags: ["أطباق", "فود", "قائمة طعام"],
      description: "تصوير ٢٠ طبق جديد للقائمة",
      isFavorite: false,
      order: 4,
      createdAt: "2025-03-21T16:00:00.000Z",
      updatedAt: "2025-03-21T16:00:00.000Z",
    },
    {
      id: "m6",
      workspaceId: DEFAULT_WORKSPACE_ID,
      clientId: "c3",
      title: "مكتبة أجواء المطعم",
      url: "https://drive.google.com/drive/folders/example6",
      shootDate: "2025-03-05",
      type: "library",
      tags: ["بي رول", "أجواء", "ديكور", "إضاءة"],
      description: "لقطات أجواء وديكور وإضاءة المطعم - مرجع دائم",
      isFavorite: true,
      order: 5,
      createdAt: "2025-03-06T13:00:00.000Z",
      updatedAt: "2025-03-06T13:00:00.000Z",
    },
  ],
  dailyTasks: [],
};
